apiVersion: v1
kind: Template
metadata:
  name: drupal8-standalone
  annotations:
    openshift.io/display-name: "Drupal 8 Luggage Application"
    description: "Ephemorial Drupal 8 Luggage install"
    iconClass: "icon-drupal"
    tags: "drupal,php"
message: >-
  Your site is located at ${SITE}.cloud.las.iastate.edu. 
  Admin password set to ${ADMINPASSWORD}
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: drupal8-${SITE}-app
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Build the drupal8 site
    creationTimestamp: null
    labels:
      app: drupal8-${SITE}-app
    name: drupal8-${SITE}-app
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: drupal8-${SITE}-app:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: ssh://git@github.com/isubit/iastate8-project.git
        ref: ${IASTATE8PROJECTGITREF}
      sourceSecret:
        name: sshsecret-drupal8os
      secrets:
      - secret:
          name: sshsecret-drupal8os
      - secret:
          name: secret-drupal8db
        destinationDir: /opt/app-root/src/db
    strategy:
      sourceStrategy:
        env:
        - name: SITE
          value: ${SITE}
        - name: SITEPASSWORD
          value: ${SITEPASSWORD}
        - name: SITEHASHSALT
          value: ${SITEHASHSALT}
        - name: DRUPALADMINPASSWORD
          value: ${ADMINPASSWORD}
        - name: DOCUMENTROOT
          value: /web
        from:
          kind: ImageStreamTag
          name: drupal8-builder:latest
          namespace: drupal8-standalone
      type: Source
    triggers:
    - github:
        secret: 9QNWz4DhfW-FRplnxUiC
      type: GitHub
    - generic:
        secret: J0HNfz6pFzSZClgShD0c
      type: Generic
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Drupal Deployment configurations
    creationTimestamp: null
    labels:
      app: drupal8-${SITE}-app
    name: drupal8-${SITE}-app
  spec:
    replicas: 1
    selector:
      name: drupal8-${SITE}-app
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: drupal8-${SITE}-app
        name: drupal8-${SITE}-app
      spec:
        containers:
        - image: ' '
          imagePullPolicy: Always
          name: drupal8-${SITE}-app
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - drupal8-${SITE}-app
        from:
          kind: ImageStreamTag
          name: drupal8-${SITE}-app:latest
          namespace: drupal8-standalone
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    name:  ${SITE}
  spec:
    host: ${SITE}.cloud.las.iastate.edu
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: drupal8-${SITE}-app
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes the application
    creationTimestamp: null
    labels:
      app: drupal8-${SITE}-app
    name: drupal8-${SITE}-app
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: drupal8-${SITE}-app
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
  - name: SITE
    displayName: Site Identifyer
    description: >-
      Unique Identifyer for the site like netid (all lowercase). Installation will fail 
      if database exists with this name.
    value:
    required: true 
  - name: IASTATE8PROJECTGITREF
    displayName: IAState 8 Git Branch
    description: >-
      Git branch, tag, or reference from which to build. Defaults to master
    value: 'master'
  - name: ADMINPASSWORD
    displayName: Drupal Admin Password
    description: Password used for admin authentication
    from: '[a-zA-Z0-9]{12}'
    generate: expression
  - name: SITEPASSWORD
    displayName: Drupal Database Password
    description: Password used for DB, auto generated if left blank
    from: '[a-zA-Z0-9]{16}'
    generate: expression
  - name: SITEHASHSALT
    displayName: Drupal Hash Salt
    description: >-
      Salt used in drupal site config. Set here so forms, it stays the same after rebuilds. 
      Auto generated if left blank
    from: '[a-zA-Z0-9]{73}'
    generate: expression
